name: Ultra Scalable SMTP Server
hostname: test.rellitel.ink

server: 
  host: 0.0.0.0
  port: 8080
  host_ipv6: "::"
  port_ipv6: 8080
  # IPv6_disable: true

log_dir: "./temp/logs"
dev: true

max_recipients: 4

max_clients: 3

forward: amqp
