name: Ultra Scalable SMTP Server
hostname: test.rellitel.ink

port: 8080

esmtp:
  enable: true
  tls: true
  utf8: false

tls: 
  starttls: false
  key: /home/parthka/u2smtp/temp/server.key
  cert: /home/parthka/u2smtp/temp/server.crt

log_dir: "./temp/logs"
dev: true
spf_check: false

max_recipients: -1
check_mailbox: true
max_clients: 6


amqp_conf:
  host: rellit.email
  username: rellite
  password: Rellite@Parth

client:
  try_tls: true
