name: Ultra Scalable SMTP Server
hostname: test.rellitel.ink

server: 
  host: 0.0.0.0
  port: 8080
  host_ipv6: "::"
  port_ipv6: 8080
  # IPv6_disable: true

esmtp:
  enable: true
  tls: true
  utf8: false

tls: 
  key: /home/parthka/u2smtp/temp/server.key
  cert: /home/parthka/u2smtp/temp/server.crt

log_dir: "./temp/logs"
dev: true

max_recipients: 1
check_mailbox: false

max_clients: 3

forward: redis
redis_conf:
  host: rellit.email
  port: 6379
  password: Rellite@Parth

amqp_conf:
  host: rellit.email
  username: rellite
  password: Rellite@Parth

# client: 
#   amqp_conf:
#     queue: lolking