name: Ultra Scalable SMTP Server
hostname: test.rellitel.ink

port: 8080

tls: 
  starttls: false
  key: /home/parthka/u2smtp/temp/server.key
  cert: /home/parthka/u2smtp/temp/server.crt

spf_check: false

max_recipients: -1
check_mailbox: false
max_clients: 6

amqp_conf:
  host: rellit.email
  username: rellite
  password: Rellite@Parth

client:
  try_tls: true

log_dir: "./temp/logs"
dev: true