version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - /etc/box.yaml:/etc/box.yaml
    network_mode: "host"  # Use host network mode
    restart: always  # Restart automatically

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - /etc/box.yaml:/etc/box.yaml
    network_mode: "host"  # Use host network mode
    restart: always  # Restart automatically
